# fly.toml app configuration file generated for bittersweet on 2023-09-25T23:14:23+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bittersweet"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
